# Ejemplo coturn (turnserver.conf)
# Ajusta valores y rutas para tu entorno
listening-port=3478
listening-ip=0.0.0.0
relay-ip=0.0.0.0
min-port=49152
max-port=65535
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret={{STATIC_AUTH_SECRET}}
realm={{REALM}}
# Si usas TLS (recomendado), habilita y apunta a certificados
# cert=/etc/letsencrypt/live/tu-dominio.example.com/fullchain.pem
# pkey=/etc/letsencrypt/live/tu-dominio.example.com/privkey.pem
no-stdout-log

authorize-role=peer
# Log files
log-file=/var/log/turnserver/turnserver.log
simple-log
